services:

  ihp-elm:
    image: tugboat/alpine
    default: true

    commands:
      init:
        - apk add --no-cache curl
        - install -d -m755 -o $(id -u) -g $(id -g) /nix
        - sh <(curl -L https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.9.0pre20220527_ec07a70/install)
        - ls -la /
        - ls -la "${TUGBOAT_ROOT}"
        - cd "${TUGBOAT_ROOT}" && nix build .#ihp-elm-prod

      build:
        - cd "${TUGBOAT_ROOT}" && nix build .#ihp-elm-prod

      start:
        - cd "${TUGBOAT_ROOT}/result/lib" && ../bin/RunProdServer
